apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  labels:
    app.kubernetes.io/instance: default
  name: simple-web-app-gateway
  namespace: web-app
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: simple-web-app-svc
              servicePort: 80
            path: /.*
